Show cache size

diff --git a/.github/workflows/actions/s3_cache/action.yaml b/.github/workflows/actions/s3_cache/action.yaml
--- a/.github/workflows/actions/s3_cache/action.yaml
+++ b/.github/workflows/actions/s3_cache/action.yaml
@@ -19,6 +19,18 @@ inputs:
 runs:
   using: "composite"
   steps:
+    - name: TODO REMOVE Show loaded cache size
+      if: ${{ inputs.action == 'load' }}
+      shell: bash
+      run: |
+        for path in ${{ inputs.paths }}; do
+          if [ ! -d $path ]; then
+            echo "Warning: $path not found in cache"
+          else
+            echo "Loaded size of $path:"
+            du -sh $path
+          fi
+        done
     - name: Retrieve cache
       if: ${{ inputs.action == 'load' }}
       # Many jobs access the cache in parallel an we might observe an incomplete state that isn't valid. This would fail with a checksum error. Let's not fail the CI job but continue it, later on this job will upload a new new cache as part of the regular job run.
@@ -33,7 +45,31 @@ runs:
         aws-region: eu-west-1
         bucket: ci-cache.cryfs
         key: ${{ inputs.cache_key }}
-
+    - name: Show loaded cache size
+      if: ${{ inputs.action == 'load' }}
+      shell: bash
+      run: |
+        for path in ${{ inputs.paths }}; do
+          if [ ! -d $path ]; then
+            echo "Warning: $path not found in cache"
+          else
+            echo "Loaded size of $path:"
+            du -sh $path
+          fi
+        done
+    - name: Show cache size to save
+      if: ${{ inputs.action == 'save' }}
+      shell: bash
+      run: |
+        for path in ${{ inputs.paths }}; do
+          if [ ! -d $path ]; then
+            echo "Error: $path not found"
+            # TODO exit 1
+          else
+            echo "Saving size of $path:"
+            du -sh $path
+          fi
+        done
     - name: Save cache
       # note: this access key has write access to the cache. This can't run on PRs.
       if: ${{ inputs.action == 'save' && github.event_name == 'push' }}
