[noland] Disable irrelevant CI

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -9,16 +9,16 @@ jobs:
       matrix:
         name: [""]
         os:
-          - macos-12
-          - macos-13
-          - macos-14
-          - ubuntu-20.04
-          - ubuntu-22.04
+          # - macos-12
+          # - macos-13
+          # - macos-14
+          # - ubuntu-20.04
+          # - ubuntu-22.04
           - ubuntu-24.04
         build_type:
           - Debug
-          - Release
-          - RelWithDebInfo
+          # - Release
+          # - RelWithDebInfo
         compiler:
           - compiler: gcc
             version: 7
@@ -27,154 +27,154 @@ jobs:
             cxx: g++-7
             homebrew_package: gcc@7
             apt_package: g++-7
-          - compiler: gcc
-            version: 8
-            libcxx: libstdc++11
-            cc: gcc-8
-            cxx: g++-8
-            homebrew_package: gcc@8
-            apt_package: g++-8
-          - compiler: gcc
-            version: 9
-            libcxx: libstdc++11
-            cc: gcc-9
-            cxx: g++-9
-            apt_package: g++-9
-            homebrew_package: gcc@9
-          - compiler: gcc
-            version: 10
-            libcxx: libstdc++11
-            cc: gcc-10
-            cxx: g++-10
-            apt_package: g++-10
-            homebrew_package: gcc@10
-          - compiler: gcc
-            version: 11
-            libcxx: libstdc++11
-            cc: gcc-11
-            cxx: g++-11
-            apt_package: g++-11
-            homebrew_package: gcc@11
-          - compiler: gcc
-            version: 12
-            libcxx: libstdc++11
-            cc: gcc-12
-            cxx: g++-12
-            apt_package: g++-12
-            homebrew_package: gcc@12
-          - compiler: gcc
-            version: 13
-            libcxx: libstdc++11
-            cc: gcc-13
-            cxx: g++-13
-            apt_package: g++-13
-            homebrew_package: gcc@13
-          - compiler: gcc
-            version: 14
-            libcxx: libstdc++11
-            cc: gcc-14
-            cxx: g++-14
-            apt_package: g++-14
-            homebrew_package: gcc@14
-          - compiler: clang
-            version: 7.1
-            libcxx: libc++
-            cc: clang-7
-            cxx: clang++-7
-            macos_cc: llvm@7/bin/clang
-            macos_cxx: llvm@7/bin/clang++
-            apt_package: clang-7 libc++-7-dev libc++abi-7-dev
-            homebrew_package: llvm@7
-          - compiler: clang
-            version: 8
-            libcxx: libc++
-            cc: clang-8
-            cxx: clang++-8
-            macos_cc: llvm@8/bin/clang
-            macos_cxx: llvm@8/bin/clang++
-            apt_package: clang-8 libc++-8-dev libc++abi-8-dev
-            homebrew_package: llvm@8
-          - compiler: clang
-            version: 9
-            libcxx: libc++
-            cc: clang-9
-            cxx: clang++-9
-            macos_cc: llvm@9/bin/clang
-            macos_cxx: llvm@9/bin/clang++
-            apt_package: clang-9 libc++-9-dev libc++abi-9-dev
-            homebrew_package: llvm@9
-          - compiler: clang
-            version: 10
-            libcxx: libc++
-            cc: clang-10
-            cxx: clang++-10
-            macos_cc: llvm@10/bin/clang
-            macos_cxx: llvm@10/bin/clang++
-            apt_package: clang-10 libc++-10-dev libc++abi-10-dev
-            homebrew_package: llvm@10
-          - compiler: clang
-            version: 11
-            libcxx: libc++
-            cc: clang-11
-            cxx: clang++-11
-            macos_cc: llvm@11/bin/clang
-            macos_cxx: llvm@11/bin/clang++
-            apt_package: clang-11 libc++-11-dev libc++abi-11-dev libomp5-11 libomp-11-dev
-            homebrew_package: llvm@11
-          - compiler: clang
-            version: 12
-            libcxx: libc++
-            cc: clang-12
-            cxx: clang++-12
-            macos_cc: llvm@12/bin/clang
-            macos_cxx: llvm@12/bin/clang++
-            apt_package: clang-12 libc++-12-dev libc++abi-12-dev libomp5-12 libomp-12-dev
-            homebrew_package: llvm@12
-          - compiler: clang
-            version: 13
-            libcxx: libc++
-            cc: clang-13
-            cxx: clang++-13
-            macos_cc: llvm@13/bin/clang
-            macos_cxx: llvm@13/bin/clang++
-            apt_package: clang-13 libc++-13-dev libc++abi-13-dev libomp5-13 libomp-13-dev
-            homebrew_package: llvm@13
-          - compiler: clang
-            version: 14
-            libcxx: libc++
-            cc: clang-14
-            cxx: clang++-14
-            macos_cc: llvm@14/bin/clang
-            macos_cxx: llvm@14/bin/clang++
-            apt_package: clang-14 libc++-14-dev libc++abi-14-dev libomp5-14 libomp-14-dev
-            homebrew_package: llvm@14
-          - compiler: clang
-            version: 15
-            libcxx: libc++
-            cc: clang-15
-            cxx: clang++-15
-            macos_cc: llvm@15/bin/clang
-            macos_cxx: llvm@15/bin/clang++
-            apt_package: clang-15 libc++-15-dev libc++abi-15-dev libomp5-15 libomp-15-dev
-            homebrew_package: llvm@15
-          - compiler: clang
-            version: 16
-            libcxx: libc++
-            cc: clang-16
-            cxx: clang++-16
-            macos_cc: llvm@16/bin/clang
-            macos_cxx: llvm@16/bin/clang++
-            apt_package: clang-16 libc++-16-dev libc++abi-16-dev libomp5-16 libomp-16-dev
-            homebrew_package: llvm@16
-          - compiler: clang
-            version: 17
-            libcxx: libc++
-            cc: clang-17
-            cxx: clang++-17
-            macos_cc: llvm@17/bin/clang
-            macos_cxx: llvm@17/bin/clang++
-            apt_package: clang-17 libc++-17-dev libc++abi-17-dev libomp5-17 libomp-17-dev
-            homebrew_package: llvm@17
+          # - compiler: gcc
+          #   version: 8
+          #   libcxx: libstdc++11
+          #   cc: gcc-8
+          #   cxx: g++-8
+          #   homebrew_package: gcc@8
+          #   apt_package: g++-8
+          # - compiler: gcc
+          #   version: 9
+          #   libcxx: libstdc++11
+          #   cc: gcc-9
+          #   cxx: g++-9
+          #   apt_package: g++-9
+          #   homebrew_package: gcc@9
+          # - compiler: gcc
+          #   version: 10
+          #   libcxx: libstdc++11
+          #   cc: gcc-10
+          #   cxx: g++-10
+          #   apt_package: g++-10
+          #   homebrew_package: gcc@10
+          # - compiler: gcc
+          #   version: 11
+          #   libcxx: libstdc++11
+          #   cc: gcc-11
+          #   cxx: g++-11
+          #   apt_package: g++-11
+          #   homebrew_package: gcc@11
+          # - compiler: gcc
+          #   version: 12
+          #   libcxx: libstdc++11
+          #   cc: gcc-12
+          #   cxx: g++-12
+          #   apt_package: g++-12
+          #   homebrew_package: gcc@12
+          # - compiler: gcc
+          #   version: 13
+          #   libcxx: libstdc++11
+          #   cc: gcc-13
+          #   cxx: g++-13
+          #   apt_package: g++-13
+          #   homebrew_package: gcc@13
+          # - compiler: gcc
+          #   version: 14
+          #   libcxx: libstdc++11
+          #   cc: gcc-14
+          #   cxx: g++-14
+          #   apt_package: g++-14
+          #   homebrew_package: gcc@14
+          # - compiler: clang
+          #   version: 7.1
+          #   libcxx: libc++
+          #   cc: clang-7
+          #   cxx: clang++-7
+          #   macos_cc: llvm@7/bin/clang
+          #   macos_cxx: llvm@7/bin/clang++
+          #   apt_package: clang-7 libc++-7-dev libc++abi-7-dev
+          #   homebrew_package: llvm@7
+          # - compiler: clang
+          #   version: 8
+          #   libcxx: libc++
+          #   cc: clang-8
+          #   cxx: clang++-8
+          #   macos_cc: llvm@8/bin/clang
+          #   macos_cxx: llvm@8/bin/clang++
+          #   apt_package: clang-8 libc++-8-dev libc++abi-8-dev
+          #   homebrew_package: llvm@8
+          # - compiler: clang
+          #   version: 9
+          #   libcxx: libc++
+          #   cc: clang-9
+          #   cxx: clang++-9
+          #   macos_cc: llvm@9/bin/clang
+          #   macos_cxx: llvm@9/bin/clang++
+          #   apt_package: clang-9 libc++-9-dev libc++abi-9-dev
+          #   homebrew_package: llvm@9
+          # - compiler: clang
+          #   version: 10
+          #   libcxx: libc++
+          #   cc: clang-10
+          #   cxx: clang++-10
+          #   macos_cc: llvm@10/bin/clang
+          #   macos_cxx: llvm@10/bin/clang++
+          #   apt_package: clang-10 libc++-10-dev libc++abi-10-dev
+          #   homebrew_package: llvm@10
+          # - compiler: clang
+          #   version: 11
+          #   libcxx: libc++
+          #   cc: clang-11
+          #   cxx: clang++-11
+          #   macos_cc: llvm@11/bin/clang
+          #   macos_cxx: llvm@11/bin/clang++
+          #   apt_package: clang-11 libc++-11-dev libc++abi-11-dev libomp5-11 libomp-11-dev
+          #   homebrew_package: llvm@11
+          # - compiler: clang
+          #   version: 12
+          #   libcxx: libc++
+          #   cc: clang-12
+          #   cxx: clang++-12
+          #   macos_cc: llvm@12/bin/clang
+          #   macos_cxx: llvm@12/bin/clang++
+          #   apt_package: clang-12 libc++-12-dev libc++abi-12-dev libomp5-12 libomp-12-dev
+          #   homebrew_package: llvm@12
+          # - compiler: clang
+          #   version: 13
+          #   libcxx: libc++
+          #   cc: clang-13
+          #   cxx: clang++-13
+          #   macos_cc: llvm@13/bin/clang
+          #   macos_cxx: llvm@13/bin/clang++
+          #   apt_package: clang-13 libc++-13-dev libc++abi-13-dev libomp5-13 libomp-13-dev
+          #   homebrew_package: llvm@13
+          # - compiler: clang
+          #   version: 14
+          #   libcxx: libc++
+          #   cc: clang-14
+          #   cxx: clang++-14
+          #   macos_cc: llvm@14/bin/clang
+          #   macos_cxx: llvm@14/bin/clang++
+          #   apt_package: clang-14 libc++-14-dev libc++abi-14-dev libomp5-14 libomp-14-dev
+          #   homebrew_package: llvm@14
+          # - compiler: clang
+          #   version: 15
+          #   libcxx: libc++
+          #   cc: clang-15
+          #   cxx: clang++-15
+          #   macos_cc: llvm@15/bin/clang
+          #   macos_cxx: llvm@15/bin/clang++
+          #   apt_package: clang-15 libc++-15-dev libc++abi-15-dev libomp5-15 libomp-15-dev
+          #   homebrew_package: llvm@15
+          # - compiler: clang
+          #   version: 16
+          #   libcxx: libc++
+          #   cc: clang-16
+          #   cxx: clang++-16
+          #   macos_cc: llvm@16/bin/clang
+          #   macos_cxx: llvm@16/bin/clang++
+          #   apt_package: clang-16 libc++-16-dev libc++abi-16-dev libomp5-16 libomp-16-dev
+          #   homebrew_package: llvm@16
+          # - compiler: clang
+          #   version: 17
+          #   libcxx: libc++
+          #   cc: clang-17
+          #   cxx: clang++-17
+          #   macos_cc: llvm@17/bin/clang
+          #   macos_cxx: llvm@17/bin/clang++
+          #   apt_package: clang-17 libc++-17-dev libc++abi-17-dev libomp5-17 libomp-17-dev
+          #   homebrew_package: llvm@17
           # Apple Clang
 #           - compiler: apple-clang
 #             version: xxx
@@ -650,96 +650,96 @@ jobs:
         with:
           build_type: ${{matrix.build_type}}
 
-  windows:
-    name: CI
-    strategy:
-      fail-fast: false
-      matrix:
-        name: [""]
-        os:
-          - windows-2019
-        arch:
-          - x64
-        build_type:
-          - Debug
-          - Release
-          - RelWithDebInfo
-    runs-on: ${{matrix.os}}
-    env:
-      # Setting conan cache dir to a location where our Github Cache Action can find it
-      CONAN_HOME: "D:/.conan/"
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          # Fetch all history because we need that to determine our version number
-          fetch-depth: 0
-      #TODO Ideally, all the setup actions would be in their own subaction, but Github doesn't support using third party actions (e.g. cache) from nested actions yet, see https://github.com/actions/runner/issues/862
-      - name: Setup Windows
-        uses: ./.github/workflows/actions/setup_windows
-      - name: Get ccache dir
-        id: ccache_dir
-        shell: bash
-        run: |
-          # Windows CI has backwards slashes in github.workspace, so we need to convert that to forward slashes
-          CCACHE_DIR="${{github.workspace}}/.ccache"
-          echo "ccache_dir=${CCACHE_DIR//\\//}" >> $GITHUB_OUTPUT
-      - name: Setup ccache
-        uses: ./.github/workflows/actions/ccache/setup
-        with:
-          ccache_dir: ${{steps.ccache_dir.outputs.ccache_dir}}
-          cache_key: v2-${{ runner.os }}-${{ matrix.os }}-ccache__${{matrix.build_type}}__
-      # TODO Ideally, the Setup conan cache step would be part of the build action, but Github doesn't support nested actions yet, see https://github.com/actions/runner/issues/862
-      - name: Restore conan cache
-        uses: ./.github/workflows/actions/conan/cache
-        with:
-          action: load
-          cache_key: v9-${{ runner.os }}-${{ matrix.os }}-conancache__${{matrix.build_type}}__
-      # Setup conan is after restoring the conan cache so that the cache doesn't overwrite the conan profile
-      - name: Setup conan
-        uses: ./.github/workflows/actions/conan/setup
-        with:
-          arch: "x86_64"
-          compiler: "msvc"
-          compiler_version: "192"
-          build_type: ${{ matrix.build_type }}
-      - name: Install dependencies
-        uses: ./.github/workflows/actions/conan/install_dependencies
-      - name: Build
-        uses: ./.github/workflows/actions/conan/build
-        with:
-          extra_conan_flags: "-o '&:windows_dokany_path=C:/Program Files/Dokan/DokanLibrary-2.0.6'"
-      - name: Save ccache
-        uses: ./.github/workflows/actions/ccache/cache
-        with:
-          action: 'save'
-          ccache_dir: ${{steps.ccache_dir.outputs.ccache_dir}}
-          cache_key: v2-${{ runner.os }}-${{ matrix.os }}-ccache__${{matrix.build_type}}__
-          secret_aws_access_key_id: ${{ secrets.CACHE_AWS_ACCESS_KEY_ID }}
-          secret_aws_secret_access_key: ${{ secrets.CACHE_AWS_SECRET_ACCESS_KEY }}
-      - name: Save conan cache
-        uses: ./.github/workflows/actions/conan/cache
-        with:
-          action: save
-          secret_aws_access_key_id: ${{ secrets.CACHE_AWS_ACCESS_KEY_ID }}
-          secret_aws_secret_access_key: ${{ secrets.CACHE_AWS_SECRET_ACCESS_KEY }}
-          cache_key: v9-${{ runner.os }}-${{ matrix.os }}-conancache__${{matrix.build_type}}__
-      - name: Test
-        shell: bash
-        run: |
-          set -v
-          set -e
-          cd build/${{matrix.build_type}}/test
-          ./gitversion/gitversion-test.exe
-          ./cpp-utils/cpp-utils-test.exe
-          # ./fspp/fspp-test.exe
-          ./parallelaccessstore/parallelaccessstore-test.exe
-          ./blockstore/blockstore-test.exe
-          ./blobstore/blobstore-test.exe
-          ./cryfs/cryfs-test.exe
-          # TODO Enable cryfs-cli-test on Windows
-          # ./cryfs-cli/cryfs-cli-test.exe
-      - name: CPack
-        uses: ./.github/workflows/actions/cpack
-        with:
-          build_type: ${{matrix.build_type}}
+  # windows:
+  #   name: CI
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       name: [""]
+  #       os:
+  #         - windows-2019
+  #       arch:
+  #         - x64
+  #       build_type:
+  #         - Debug
+  #         - Release
+  #         - RelWithDebInfo
+  #   runs-on: ${{matrix.os}}
+  #   env:
+  #     # Setting conan cache dir to a location where our Github Cache Action can find it
+  #     CONAN_HOME: "D:/.conan/"
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #       with:
+  #         # Fetch all history because we need that to determine our version number
+  #         fetch-depth: 0
+  #     #TODO Ideally, all the setup actions would be in their own subaction, but Github doesn't support using third party actions (e.g. cache) from nested actions yet, see https://github.com/actions/runner/issues/862
+  #     - name: Setup Windows
+  #       uses: ./.github/workflows/actions/setup_windows
+  #     - name: Get ccache dir
+  #       id: ccache_dir
+  #       shell: bash
+  #       run: |
+  #         # Windows CI has backwards slashes in github.workspace, so we need to convert that to forward slashes
+  #         CCACHE_DIR="${{github.workspace}}/.ccache"
+  #         echo "ccache_dir=${CCACHE_DIR//\\//}" >> $GITHUB_OUTPUT
+  #     - name: Setup ccache
+  #       uses: ./.github/workflows/actions/ccache/setup
+  #       with:
+  #         ccache_dir: ${{steps.ccache_dir.outputs.ccache_dir}}
+  #         cache_key: v2-${{ runner.os }}-${{ matrix.os }}-ccache__${{matrix.build_type}}__
+  #     # TODO Ideally, the Setup conan cache step would be part of the build action, but Github doesn't support nested actions yet, see https://github.com/actions/runner/issues/862
+  #     - name: Restore conan cache
+  #       uses: ./.github/workflows/actions/conan/cache
+  #       with:
+  #         action: load
+  #         cache_key: v9-${{ runner.os }}-${{ matrix.os }}-conancache__${{matrix.build_type}}__
+  #     # Setup conan is after restoring the conan cache so that the cache doesn't overwrite the conan profile
+  #     - name: Setup conan
+  #       uses: ./.github/workflows/actions/conan/setup
+  #       with:
+  #         arch: "x86_64"
+  #         compiler: "msvc"
+  #         compiler_version: "192"
+  #         build_type: ${{ matrix.build_type }}
+  #     - name: Install dependencies
+  #       uses: ./.github/workflows/actions/conan/install_dependencies
+  #     - name: Build
+  #       uses: ./.github/workflows/actions/conan/build
+  #       with:
+  #         extra_conan_flags: "-o '&:windows_dokany_path=C:/Program Files/Dokan/DokanLibrary-2.0.6'"
+  #     - name: Save ccache
+  #       uses: ./.github/workflows/actions/ccache/cache
+  #       with:
+  #         action: 'save'
+  #         ccache_dir: ${{steps.ccache_dir.outputs.ccache_dir}}
+  #         cache_key: v2-${{ runner.os }}-${{ matrix.os }}-ccache__${{matrix.build_type}}__
+  #         secret_aws_access_key_id: ${{ secrets.CACHE_AWS_ACCESS_KEY_ID }}
+  #         secret_aws_secret_access_key: ${{ secrets.CACHE_AWS_SECRET_ACCESS_KEY }}
+  #     - name: Save conan cache
+  #       uses: ./.github/workflows/actions/conan/cache
+  #       with:
+  #         action: save
+  #         secret_aws_access_key_id: ${{ secrets.CACHE_AWS_ACCESS_KEY_ID }}
+  #         secret_aws_secret_access_key: ${{ secrets.CACHE_AWS_SECRET_ACCESS_KEY }}
+  #         cache_key: v9-${{ runner.os }}-${{ matrix.os }}-conancache__${{matrix.build_type}}__
+  #     - name: Test
+  #       shell: bash
+  #       run: |
+  #         set -v
+  #         set -e
+  #         cd build/${{matrix.build_type}}/test
+  #         ./gitversion/gitversion-test.exe
+  #         ./cpp-utils/cpp-utils-test.exe
+  #         # ./fspp/fspp-test.exe
+  #         ./parallelaccessstore/parallelaccessstore-test.exe
+  #         ./blockstore/blockstore-test.exe
+  #         ./blobstore/blobstore-test.exe
+  #         ./cryfs/cryfs-test.exe
+  #         # TODO Enable cryfs-cli-test on Windows
+  #         # ./cryfs-cli/cryfs-cli-test.exe
+  #     - name: CPack
+  #       uses: ./.github/workflows/actions/cpack
+  #       with:
+  #         build_type: ${{matrix.build_type}}
